export default {
    id: {
        _hide:true
    },
    skuQcResult:{
        showType:'qc',
        value:'Waiting QC'
    },
    skuInventoryStatusDictCode:{},
    skuCode:{},
    customerSkuCode:{},
    factorySkuCode:{},
    skuNameCn:{},
    skuBrand:{},
    skuDesign:{},
    packingMethodCn:{},
    innerCartonPackingMethodCn:{},
    deliveryDate:{
        showType:'date'
    },
    skuUnitDictCode:{},
    lengthUnitDictCode:{},
    volumeUnitDictCode:{},
    weightUnitDictCode:{},
    inboundNo:{},
    orderSkuQty:{},
    expectQcQty:{
        key:'expectQcQty',
        showType:'number'
    },
    samplingRate:{
        key:'samplingRate',
        showType:'number'
    },
    unqualifiedProcessingMode:{
        key:'unqualifiedProcessingMode',
        showType:'input'
    },
    skuLength:{},
    skuWidth:{},
    skuHeight:{},
    skuNetWeight:{},
    outerCartonSkuQty:{},
    actQtyOfOuterCarton:{
        fromService:true
    },
    //外箱中包数(create的时候不要)
    actQuantityOfInnerBoxOuterCarton:{
        fromService:true
    },
    //中包产品数(create的时候不要)
    actualQuantityInnerCarton:{
        fromService:true
    },
    innerCartonLength:{
        fromService:true
    },
    innerCartonWidth:{
        fromService:true
    },
    innerCartonHeight:{
        fromService:true
    },
    innerCartonNetWeight:{
        fromService:true
    },
    innerCartonGrossWeight:{
        fromService:true
    },
    innerCartonVolume:{
        fromService:true
    },
    outerCartonLength:{
        fromService:true
    },
    outerCartonWidth:{
        fromService:true
    },
    outerCartonHeight:{
        fromService:true
    },
    netWeightOfOuterCarton:{
        fromService:true
    },
    outerCartonVolume:{
        fromService:true
    },
    grossWeightOfOuterCarton:{
        fromService:true
    },
    actualProductTotalCTNS:{
        fromService:true
    },
    qualifiedProductsTotalCTNS:{
        fromService:true
    },
    unqualifiedProductTotalCTNS:{
        fromService:true
    },
    actProductQuantity:{
        fromService:true
    },
    qualifiedProductsTotalQTYS:{
        fromService:true
    },
    unqualifiedProductsQTY:{
        fromService:true
    },
    qualifiedProductTotalNW:{
        fromService:true
    },
    unqualifiedProductTotalNW:{
        fromService:true
    },
    qualifiedProductsTotalCBM:{
        fromService:true
    },
    unqualifiedProductsTotalCBM:{
        fromService:true
    },
    qualifiedProductTotalGW:{
        fromService:true
    },
    unqualifiedProductTotalGW:{
        fromService:true
    },
    unqualifiedType:{
        fromService:true
    },
    skuBarCode:{},
    productBarCodeResults:{
        fromService:true
    },
    skuLabel:{},
    productLabelResults:{
        fromService:true
    },
    innerPackingBarCode:{},
    innerPackingBarCodeResults:{
        fromService:true
    },
    outerCartonBarCode:{},
    outerCartonBarCodeResults:{
        fromService:true
    },
    shippingMark:{},
    outerCartonMarksResults:{
        fromService:true
    },
    qcPic:{
        fromService:true
    },
    checkOuterCartons:{
        fromService:true
    },
    remark:{
        fromService:true
    },

}