export default {
    skuId:{
        _hide:true
    },
    canCreateQc:{
        _hide:true
    },
    id:{
        _hide:true
    },
    skuInventoryStatusDictCode:{
        _hide:true
    },
    orderNo:{},
    skuBarCode:{},
    skuCode:{},
    inboundNo:{},
    skuNameEn:{},
    skuNameCustomer:{},
    skuNameCn:{},
    skuMaterialCn:{},
    skuMaterialEn:{},
    factorySkuCode:{},
    customerSkuCode:{},
    skuDescEn:{},
    skuDescCn:{},
    skuBrand:{},
    innerCartonVolume:{},
}