export default {
    quotationNo:{},
    orderNo:{},
    entryDt:{},
    incoterm:{},
    incotermArea:{},
    currency:{},
    unitPrice:{},
    skuPrice:{},
    totalQty:{},
    actDeliveryDt:{},
    confirmQcDt:{},
    actDepartureDt:{},
    totalContainerQty:{},
    skuQty:{},
}