export default {
  createInquiry: {
    icon: '', link: '/negotiation/createInquiry',
    customer: true,
    supplier: false,
    server: false,
    defaultShow: true,
  },
  createOrder: {
    icon: '', link: '/order/creat',
    customer: true,
    supplier: false,
    server: false,
    defaultShow: true,
  },
  addProduct: {
    icon: '', link: '',
    customer: false,
    supplier: true,
    server: false,
    defaultShow: true,
  },
  createInbound: {
    icon: '', link: '',
    customer: false,
    supplier: true,
    server: false,
    defaultShow: true,
  },
  createQC: {
    icon: '', link: '',
    customer: true,
    supplier: false,
    server: false,
    defaultShow: true,
  },
  createOutbound: {
    icon: '', link: '',
    customer: false,
    supplier: false,
    server: false,
    defaultShow: true,
  },
  placeLogisticPlan: {
    icon: '', link: '/logistic/placeLogisticPlan',
    customer: true,
    supplier: false,
    server: false,
    defaultShow: true,
  },
  // placeLogisticOrder: {icon: '', link: ''},
  message: {
    icon: '', link: '/message/index',
    customer: true,
    supplier: true,
    server: true,
  },
  sourcingOverview: {
    icon: '', link: '/product/sourcing',
    customer: true,
    supplier: false,
    server: false,
  },
  bookmarkOverview: {
    icon: '', link: '/product/bookmark',
    customer: true,
    supplier: false,
    server: false,
  },
  compareInquiryOverview: {
    icon: '', link: '/negotiation/compareDetail/inquiry',
    customer: true,
    supplier: false,
    server: false,
  },
  supplierOverview: {
    icon: '', link: '/supplier/sourcing',
    customer: true,
    supplier: false,
    server: false,
  },
  inquiry: {
    icon: '', link: '/negotiation/inquiry',
    customer: true,
    supplier: false,
    server: false,
  },
  orderOverview: {
    icon: '', link: '/order/overview',
    customer: true,
    supplier: true,
    server: false,
  },
  warehouse: {
    icon: '', link: '/warehouse/overview',
    customer: true,
    supplier: true,
    server: false,
  },
  inbound: {
    icon: '', link: '',
    customer: false,
    supplier: true,
    server: false,
  },
  outbound: {
    icon: '', link: '',
    customer: false,
    supplier: true,
    server: false,
  },
  QCOrderOverview: {
    icon: '', link: '/warehouse/qcOverview',
    customer: true,
    supplier: true,
    server: true,
  },
  logisticPlanOverview: {
    icon: '', link: '/logistic/plan',
    customer: true,
    supplier: false,
    server: false,
  },
  loardinglistOrderOverview: {
    icon: '', link: '/logistic/planDetail',
    customer: true,
    supplier: true,
    server: false,
  },
  track: {
    icon: '', link: '/track/index',
    customer: true,
    supplier: false,
    server: false,
  },
  compareSupplierOverview: {
    icon: '', link: '/supplier/compare',
    customer: true,
    supplier: false,
    server: false,
  },
  productOverview: {
    icon: '', link: '',
    customer: false,
    supplier: true,
    server: false,
  },
  customerOverview: {
    icon: '', link: '',
    customer: false,
    supplier: true,
    server: true,
  },
}
