export default {
  createInquiry: {},
  createOrder: {},
  addProduct: {},
  createInbound: {},
  createQC: {},
  createOutbound: {},
  placeLogisticPlan: {},
  placeLogisticOrder: {},
  message: {},
  sourcingOverview: {},
  bookmarkOverview: {},
  compareInquiryOverview: {},
  supplierOverview: {},
  inquiryOverview: {},
  orderOverview: {},
  warehouse: {},
  inbound: {},
  outbound: {},
  QCOrderOverview: {},
  logisticPlanOverview: {},
  logisticOverview: {},
  track: {},
  compareSupplierOverview: {},
  productOverview: {},
  customerOverview: {},
}
