export default {
    orderNo: {
        key: 'orderNo',
        value: '',
        ismodify: false,
        isDefaultEdit: true,
        rules: [],
        type: 'text',
    },
    orderDate: {
        key: 'orderDate',
        value: '',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'datepicker',
    },
    customerOrderNo: {
        key: 'customerOrderNo',
        value: '',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'text',
    },
    customerName: {
        key: 'customerName',
        value: '',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'text',
    },
    customerNo: {
        key: 'customerNo',
        value: '',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'text',
    },
    supplierOrderNo: {
        key: 'supplierOrderNo',
        value: '',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'text',
    },
    supplierName: {
        key: 'supplierName',
        value: '',
        ismodify: false,
        isDefaultEdit: true,
        rules: [],
        type: 'text',
    },
    supplierNo: {
        key: 'supplierNo',
        value: '',
        ismodify: false,
        isDefaultEdit: true,
        rules: [],
        type: 'text',
    },
    quotationNo: {
        key: 'quotationNo',
        value: '',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'text',
    },
    orderStatus: {
        key: 'orderStatus',
        value: '',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'select',
    },
    deliveryDate: {
        key: 'deliveryDate',
        value: '',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'datepicker',
    },
    incoterm: {
        key: 'incoterm',
        value: '',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'select',
    },
    incortermAea: {
        key: 'incortermAea',
        value: '',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'text',
    },
    payment: {
        key: 'payment',
        value: '',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'text',
    },
    lcNo: {
        key: 'lcNo',
        value: '',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'text',
    },
    paymentDays: {
        key: 'paymentDays',
        value: '',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'text',
    },
    paymentStatus: {
        key: 'paymentStatus',
        value: '',
        ismodify: false,
        isDefaultEdit: true,
        rules: [],
        type: 'text',
    },
    departureCountry: {
        key: 'departureCountry',
        value: '',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'text',
    },
    departurePort: {
        key: 'departurePort',
        value: '',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'text',
    },
    destinationCountry: {
        key: 'destinationCountry',
        value: '',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'text',
    },
    destinationPort: {
        key: 'destinationPort',
        value: '',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'text',
    },
    transportationWay: {
        key: 'transportationWay',
        value: '',
        ismodify: false,
        isDefaultEdit: true,
        rules: [],
        type: 'select',
    },
    customerAgreementNumber: {
        key: 'customerAgreementNumber',
        value: '',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'text',
    },
    customerAgreementDate: {
        key: 'customerAgreementDate',
        value: '',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'datepicker',
    },
    remark: {
        key: 'remark',
        value: '',
        ismodify: false,
        isDefaultEdit: false,
        rules: [],
        type: 'textarea',
    }
}
