export default {
    label:{
        _important:true,
        _title:'Remark'
    },
    _remark:{
        _hide:true
    },
    skuId:{
        _hide:true
    },
    skuSupplierCode:{
        _hide:true
    },
    skuPic:{
        _slot:'skuPic',
        type:'pic',
        _image:true
        // disabled:true
    },
    skuNameEn:{
        _disabled:true
    },
    skuNameCn:{
        _slot:'skuNameCn',
        _disabled:true
    },
    skuDescCn:{
        _disabled:true
    },
    skuDescEn:{
        _disabled:true
    },
    skuDescCustomer:{
        _disabled:true
    },
    skuNameCustomer:{
        _disabled:true
    },
    skuCustomerSkuCode:{
        _disabled:true
    },
    skuCode:{
        _disabled:true
    },
    skuSupplierName:{
        _disabled:true
    },
    skuFobCurrency:{
        _slot:'skuFobCurrency',
        type:'currency'
    },
    skuFobPrice:{

    },
    skuFobPort:{},
    skuExwCurrency:{},
    skuExwPrice:{},
    skuCifCurrency:{},
    skuCifPrice:{},
    skuCifPort:{},
    skuDduCurrency:{},
    skuDduPrice:{},
    skuDduPort:{},
    skuUnit:{},
    skuMaterialEn:{},
    skuMaterialCn:{},
    skuQty:{},
    skuPrice:{},
    skuQualifiedQty:{},
    skuUntestedQty:{},
    skuDeliveredQty:{},
    skuUndeliveredQty:{},
    skuRateValueAddedTax:{},
    skuTaxRefundRate:{},
    skuColourEn:{},
    skuColourCn:{},
    skuMinOrderQty:{},
    skuDeliveryDates:{},
    skuDesign:{},
    skuCategoryOne:{},
    // skuCategoryTwo:{},
    // skuCategoryThree:{},
    // skuCategoryFour:{},
    skuCustomsCode:{},
    skuCustomsNameCn:{},
    skuCustomsNameEn:{},
    skuTradeMarkEn:{},
    skuTradeMarkCn:{},
    skuCommodityInspectionCn:{},
    skuCommodityInspectionEn:{},
    skuDeclareElement:{},
    skuOrigin:{},
    skuInspectQuarantineCategory:{},
    skuUnitWeight:{},
    skuUnitLength:{},
    skuUnitVolume:{},
    skuLength:{},
    skuWidth:{},
    skuHeight:{},
    skuNetWeight:{},
    // skuGrossWeight:{},
    skuVolume:{},
    skuMethodPkgEn:{},
    skuMethodPkgCn:{},
    skuInnerCartonUnit:{},
    skuInnerCartonQty:{},
    skuInnerCartonLength:{},
    skuInnerCartonWidth:{},
    skuInnerCartonHeight:{},
    skuInnerCartonWeightNet:{},
    skuInnerCartonRoughWeight:{},
    skuInnerCartonVolume:{},
    skuInnerCartonDesc:{},
    skuInnerCartonMethodEn:{},
    skuInnerCartonMethodCn:{},
    skuOuterCartonUnit:{},
    skuOuterCartonDesc:{},
    skuInnerCartonOuterNum:{},
    skuOuterCartonQty:{},
    skuOuterCartonLength:{},
    skuOuterCartonWidth:{},
    skuOuterCartonHeight:{},
    skuOuterCartonNetWeight:{},
    skuOuterCartonRoughWeight:{},
    skuOuterCartonVolume:{},
    skuOuterCartonMethodEn:{},
    skuOuterCartonMethodCn:{},
    skuBrand:{},
    skuApplicableAge:{},
    skuExpireDates:{},
    skuExpireUnit:{},
    skuComments:{},
    skuStatus:{},
    skuSaleStatus:{},
    skuLabel:{},
    skuBarCode:{},
    skuInnerPackBarCode:{},
    skuInnerPackLabel:{},
    skuInnerPackCode:{},
    skuShippingMarks:{},
    skuOuterCartonBarCode:{},
    skuOuterCartonCode:{},
    skuLabelPic:{},
    skuLabelDesc:{},
    skuPkgMethodPic:{},
    skuInnerCartonPic:{},
    skuOuterCartonPic:{},
    skuSample:{},
    skuSampleQty:{},
    skuSamplePrice:{},
    skuQuotationNo:{},
    skuRemarkOne:{},
    skuRemarkTwo:{},
    skuRemarkThree:{},
    skuAdditionalOne:{},
    skuAdditionalTwo:{},
    skuAdditionalThree:{},
    skuAdditionalFour:{},
}