export default {
  // logistic
  gei_plan_list: ['/logistics/plan/pageByPlanNo', 'BASE_URL'],
  get_transportation_list: ['/logistics/plan/pageByUnit', 'BASE_URL'],
  get_sku_list: ['/logistics/plan/pageBySkuCode', 'BASE_URL'],
  get_dictionary: ['/code/part', 'UMETA_URL'],
  delete_by_ids: ['/logistics/plan/deleteByIds', 'BASE_URL'],
  get_new_logistics_no: ['/logistics/plan/getNo', 'BASE_URL'],
  get_currency: ['/currency/all', 'UMETA_URL'],
  get_container_type: ['/containertype/all','UMETA_URL'],
  get_plan_details: ['/logistics/plan/get/', 'BASE_URL'],
  get_order_details: ['/logistics/order/get/', 'BASE_URL'],
  get_payment_list: ['/payment/list/', 'BASE_URL'],
  get_product_history: ['/logistics/plan/getProductHistory', 'BASE_URL'],
  get_order_list_with_page: ['/order/skuAllPage', 'BASE_URL'],
  get_loading_list_plan: ['/logistics/order/pageByPlanNo', 'BASE_URL'],
  get_loading_list_unit: ['/logistics/order/pageByUnit', 'BASE_URL'],
  get_loading_list_sku: ['/logistics/order/pageBySkuCode', 'BASE_URL'],
  update_logistic_plan: ['/logistics/plan/modify', 'BASE_URL'],
  send_logistic_plan: ['/logistics/plan/send', 'BASE_URL'],
  send_draft_logistic_plan: ['/logistics/plan/sendDraft', 'BASE_URL'],
  save_draft_logistic_plan: ['/logistics/plan/saveDraft', 'BASE_URL'],
  get_payment_no: ['/payment/genNo', 'BASE_URL'],
  save_plan_payment: ['/payment/save','BASE_URL'],
  update_plan_payment: ['/payment/update', 'BASE_URL'],
  abandon_plan_payment: ['/payment/abandon', 'BASE_URL'],
  recover_plan_payment: ['/payment/recover', 'BASE_URL'],
  get_order_supplier: ['/logistics/order/getSupplier', 'BASE_URL'],
  get_plan_supplier: ['/logistics/plan/getSupplier', 'BASE_URL'],
  get_plan_rate: ['/logistics/plan/getRate', 'BASE_URL'],
  logistics_plan_confirm: ['/logistics/plan/confirm', 'BASE_URL'],
  logistics_plan_cancel: ['/logistics/plan/cancel', 'BASE_URL'],
  logistics_order_cancelByIds: ['/logistics/order/cancelByIds', 'BASE_URL'],
  logistics_plan_getSupplierIds: ['/logistics/plan/getSupplierIds', 'BASE_URL'],
}
